device_db: ./device_db.py
devices:
  adc: [samplerA]
  dac: [zotinoA]
  dds: [urukulA]
  ttl: [ttlA]
scripts:
  - test_scripts.py
sequence_format: yml
sequences_path: ./sequences.json
timestep_unit: ms
control_port: 1107
broadcast_port: 1205
